### ISSUE TITLE
node.js version

### ISSUE THREAD

**Issue by Phalanstere** [colinbdclark/Flocking#131] opened 2015-10-17 10:36 UTC
Dear Colin,

trying to embed Flocking.js in a node.js environment, I entcountered a few problems.

First: running the **npm install** I received an error telling me:

```javascript
   Failed at the speaker@0.2.6 install script 'node-gyp rebuild'.
``` 
Since it's not your package, I think you can do very little about it.

But the second problem seems to be due to the flocking package.
After requiring the packages as recommend

```javascript
   var fluid = require("infusion"),
    flock = fluid.require("flocking");
``` 
and having browserified the code, I ran into the problem of a missing dependeny:

```javascript
Uncaught Error: Cannot find module '/node_modules/infusion/src/module/includes.json'
``` 

I trried to embed flocking.js the old fashioned way, by requiring it through: 

```javascript
var flock = require("./flocking-all.min.js"); 
``` 

but then the browserified code complains about a missing jquery, and won't stop, even if jquery is required,
What can I do?

**Comment by colinbdclark** [comment] 2015-10-17 14:24
Which version of Node.js are you using?

**Comment by colinbdclark** [comment] 2015-10-17 18:35
Hi @Phalanstere, I realized that the documentation for using Flocking with Node.js was pretty out of date and overly complex. I've updated it and tested with both Node.js 0.12 and 4.2.1, and it seems to work quite nicely. Let me know if this solves your issues.

Here is the documentation for the stable 0.1 release: https://github.com/colinbdclark/Flocking/blob/0.1.x/docs/nodejs.md

**Comment by Phalanstere** [comment] 2015-10-18 09:07
Dear Colin,

hm... I've updated my node version (0.10.x) to 0.12.7 - but to no avail. [System Ubuntu 14.04]
There is a (I guess a post install) script  errror - which terminates the process. 
 
compilation terminated.
make: *** [Release/obj.target/midi/src/node-midi.o] Fehler 1

Looking into the node_modules folder I can see there is no flocking dir.

**Comment by colinbdclark** [comment] 2015-10-18 14:28
It's hard to debug your issue without the full error log. Can you post it?

One thing to double check is that you have <code>libasound2-dev</code> installed on your Ubuntu system. It's a requirement of both node-midi and node-speaker, two key third-party libraries used by Flocking. I've updated the documentation with instructions on how to install it.

**Comment by colinbdclark** [comment] 2015-11-24 15:25
@Phalanstere were you able to resolve this issue? Can I close it, or is there more I can help with?

**Comment by colinbdclark** [comment] 2015-12-04 18:50
Closing due to inactivity and a lack of sufficient information to reproduce the issue.

**Closed by colinbdclark** 2015-12-04 18:50 UTC
